#!/bin/sh

cmd=''

# MACOS
if [ $(uname -o) = "Darwin" ]; then

  cmd='ln -sf'

  # kitty
  kitty_config="$HOME/.config/kitty/kitty.conf"
  inset_c="include $PWD/kitty/dinge.conf"

  if [ $(grep -c "${inset_c}" "${kitty_config}") == '0' ]; then
    echo "\n${inset_c}" >> ${kitty_config}
  fi
  # -----------------

  # zls
  #${cmd} "$PWD/zls/zls.json" "$HOME/Library/Application Support/zls.json"
  # -----------------

  # vscode
  ${cmd} "$PWD/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
  ${cmd} "$PWD/vscode/keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
  # -----------------

# LINUX
else

  cmd='cp -R'

  # ranger
  mkdir -p "$HOME/.config/ranger"
  ${cmd} "$PWD/arch/config/ranger/rc.conf" "$HOME/.config/ranger/"

  # npm
  mkdir -p "$HOME/core/library" "$HOME/core/library/npm-global" "$HOME/core/library/npm-cache"
  ${cmd} "$PWD/arch/d.npmrc" "$HOME/.npmrc"

  if [ $(uname -n) = "de-arch" ]; then
    # xorg
    ${cmd} "$PWD/arch/d.xinitrc" "$HOME/.xinitrc"
    ${cmd} "$PWD/arch/d.Xresources" "$HOME/.Xresources"
    ${cmd} "$PWD/arch/d.xprofile" "$HOME/.xprofile"
    ${cmd} "$PWD/arch/config/user-dirs.dirs" "$HOME/.config/user-dirs.dirs"

    # gtk
    mkdir -p "$HOME/.config/gtk-3.0"
    ${cmd} "$PWD/arch/config/gtk-3.0/gtk.css" "$HOME/.config/gtk-3.0/"
    ${cmd} "$PWD/arch/config/gtk-3.0/settings.ini" "$HOME/.config/gtk-3.0/"
    ${cmd} "$PWD/arch/config/gtk-3.0/bookmarks" "$HOME/.config/gtk-3.0/bookmarks"
    ${cmd} "$PWD/arch/d.gtkrc-2.0" "$HOME/.gtkrc-2.0"

    mkdir -p "$HOME/.config/gtk-4.0"
    ${cmd} "$PWD/arch/config/gtk-4.0/gtk.css" "$HOME/.config/gtk-4.0/"
    ${cmd} "$PWD/arch/config/gtk-4.0/settings.ini" "$HOME/.config/gtk-4.0/"
    ${cmd} "$PWD/arch/config/gtk-4.0/bookmarks" "$HOME/.config/gtk-4.0/bookmarks"

    # dwm script & wallpapers -> ding-e/dot.arch
    mkdir -p "$HOME/.dwm"
    ${cmd} "$PWD/arch/dwm/autostart.sh" "$HOME/.dwm/"
    ${cmd} "$PWD/arch/dwm/bin" "$HOME/.dwm/"
    ${cmd} "$PWD/arch/dwm/scripts" "$HOME/.dwm/"

    # i3wm
    mkdir -p "$HOME/.config/i3/log"
    ${cmd} "$PWD/arch/config/i3/config" "$HOME/.config/i3/"

    # alacritty
    mkdir -p "$HOME/.config/alacritty"
    ${cmd} "$PWD/arch/config/alacritty/alacritty.toml" "$HOME/.config/alacritty/"

    # dunst
    mkdir -p "$HOME/.config/dunst"
    ${cmd} "$PWD/arch/config/dunst/dunstrc" "$HOME/.config/dunst/dunstrc"

    # morc_menua & dmenu
    mkdir -p "$HOME/.config/morc_menu"
    ${cmd} "$PWD/arch/config/morc_menu/morc_menu_v1.conf" "$HOME/.config/morc_menu/"
    ${cmd} "$PWD/arch/config/dmenurc" "$HOME/.config/dmenurc"

    # chromium flags
    ${cmd} "$PWD/arch/config/chromium-flags.conf" "$HOME/.config/"

    # rofi
    mkdir -p "$HOME/.config/rofi"
    ${cmd} "$PWD/arch/config/rofi/config.rasi" "$HOME/.config/rofi/"
    ${cmd} "$PWD/arch/config/rofi/dinge.rasi" "$HOME/.config/rofi/"
    ${cmd} "$PWD/arch/config/rofi/gruvbox-common.rasi" "$HOME/.config/rofi/"

    # sound
    ${cmd} "$PWD/arch/d.asoundrc" "$HOME/.asoundrc"
  fi
# -----------------
fi

# zsh
${cmd} "$PWD/ohmyzsh/Chicago95.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/ohmyzsh/Chicago95_Dinge.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/ohmyzsh/dinge.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/ohmyzsh/dinge-minimal.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/d.zshrc" "$HOME/.zshrc"
# -----------------

# tmux
${cmd} "$PWD/d.tmux.conf" "$HOME/.tmux.conf"
# -----------------

# nvim nvchad - 2.0
# mkdir -p "$HOME/.config/nvim/" "$HOME/.config/nvim/lua"
# ${cmd} "$PWD/nvim-nvchad/custom" "$HOME/.config/nvim/lua"
# ${cmd} "$PWD/nvim-nvchad/after" "$HOME/.config/nvim"
# ${cmd} "$PWD/d.editorconfig" "$HOME/.editorconfig"

# nvim nvchad - 2.5
# git clone https://github.com/NvChad/starter ~/.config/nvim
# nvim目录存在，则备份
if [ -d "$HOME/.config/nvim" ]; then
    mv "$HOME/.config/nvim" "$HOME/.config/nvim-dot-$(date +%s)"
fi
mkdir -p "$HOME/.config/nvim/"
cp "$PWD/nvim-nvchad/LICENSE"  "$PWD/nvim-nvchad/init.lua" "$HOME/.config/nvim"
${cmd} "$PWD/nvim-nvchad/lua" "$HOME/.config/nvim"
${cmd} "$PWD/nvim-nvchad/after" "$HOME/.config/nvim"
${cmd} "$PWD/nvim-nvchad/.stylua.toml" "$HOME/.config/nvim"
${cmd} "$PWD/d.editorconfig" "$HOME/.editorconfig"
# -----------------

# vim
mkdir -p "$HOME/.vim/" "$HOME/.vim/autoload" "$HOME/.vim/plugged"
${cmd} "$PWD/vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
${cmd} "$PWD/d.vimrc" "$HOME/.vimrc"
# -----------------

