#!/bin/sh


# 用於linux下的配置連接
# ===========================================================

# sh -c ohmyzsh/omz.sh
# git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
# --------------------------------

# backup
mv "$HOME/.tmux.conf"             "$HOME/.tmux.conf.b"
mv "$HOME/.zshrc"                 "$HOME/.zshrc.b"
mv "$HOME/.vimrc"                 "$HOME/.vimrc.b"
mv "$HOME/.vim"                   "$HOME/.vim.b"
mv "$HOME/.config/nvim"           "$HOME/.config/nvim.b"
mv "$HOME/.config/ranger/rc.conf" "$HOME/.config/ranger/rc.config.b"

# tmux
cp "$PWD/linux/d.tmux.conf" "$HOME/.tmux.conf"

# zsh
cp "$PWD/ohmyzsh/Chicago95.zsh-theme" "$HOME/.oh-my-zsh/themes/"
cp "$PWD/ohmyzsh/Chicago95_Dinge.zsh-theme" "$HOME/.oh-my-zsh/themes/"
cp "$PWD/ohmyzsh/dinge.zsh-theme" "$HOME/.oh-my-zsh/themes/"
cp "$PWD/linux/d.zshrc" "$HOME/.zshrc"

# nvim nvchad
cp "$PWD/nvim-nvchad/custom" "$HOME/.config/nvim/lua"

# vim
mkdir "$HOME/.vim/" "$HOME/.vim/autoload" "$HOME/.vim/plugged"
cp "$PWD/vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
cp "$PWD/linux/d.vimrc" "$HOME/.vimrc"

# ranger
cp "$PWD/linux/ranger.conf" "$HOME/.config/ranger/rc.conf"

