#!/bin/sh

cmd=''

# sh -c ohmyzsh/omz.sh
# git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
# --------------------------------

# MACOS
if [ $(uname -o) = "Darwin" ]; then

  cmd='ln -sf'

  # kitty
  ${cmd} "$PWD/kitty/kitty.conf" "$HOME/.config/kitty/"
  ${cmd} "$PWD/kitty/kitty_search" "$HOME/.config/kitty/"
  # -----------------

  # zls
  ${cmd} "$PWD/zls/zls.json" "$HOME/Library/Application Support/zls.json"
  # -----------------

  # vscode
  ${cmd} "$PWD/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
  ${cmd} "$PWD/vscode/keybindings.json" "$HOME/Library/Application Support/Code/User/keybindings.json"
  # -----------------

# LINUX
else

  cmd='cp -R'

  # backup
  # mv "$HOME/.zshrc"                 "$HOME/.zshrc.b"
  # mv "$HOME/.tmux.conf"             "$HOME/.tmux.conf.b"
  # mv "$HOME/.vimrc"                 "$HOME/.vimrc.b"
  # mv "$HOME/.vim"                   "$HOME/.vim.b"
  # mv "$HOME/.config/nvim"           "$HOME/.config/nvim.b"
  # mv "$HOME/.config/ranger/rc.conf" "$HOME/.config/ranger/rc.config.b"
  # -----------------

  # ranger
  mkdir -p "$HOME/.config/ranger"
  ${cmd} "$PWD/ranger/rc.conf" "$HOME/.config/ranger/rc.conf"

  # npm
  mkdir -p "$HOME/core/library" "$HOME/core/library/npm-global" "$HOME/core/library/npm-cache"
  ${cmd} "$PWD/other/d.npmrc" "$HOME/.npmrc"

# -----------------
fi

# zsh
${cmd} "$PWD/ohmyzsh/Chicago95.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/ohmyzsh/Chicago95_Dinge.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/ohmyzsh/dinge.zsh-theme" "$HOME/.oh-my-zsh/themes/"
${cmd} "$PWD/d.zshrc" "$HOME/.zshrc"
# -----------------

# tmux
${cmd} "$PWD/d.tmux.conf" "$HOME/.tmux.conf"
# -----------------

# nvim nvchad
${cmd} "$PWD/nvim-nvchad/custom" "$HOME/.config/nvim/lua"
# -----------------
 
# vim
mkdir -p "$HOME/.vim/" "$HOME/.vim/autoload" "$HOME/.vim/plugged"
${cmd} "$PWD/vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
${cmd} "$PWD/d.vimrc" "$HOME/.vimrc"
# -----------------

